FROM --platform=linux/arm/v5 growflavor/ev3images:ev3dev10imgv02b

SHELL ["/bin/bash", "-c"]

RUN mkdir /roboliga_build


RUN apt update
RUN apt upgrade -y
RUN apt install libcurl4-openssl-dev

# Nadgradnja orodja cmake, ki je potrebno za namestitev knjižnice scipy, traja več ur
# WORKDIR /roboliga_build
# RUN wget https://github.com/Kitware/CMake/releases/download/v3.30.5/cmake-3.30.5.tar.gz
# RUN tar -zxvf cmake-3.30.5.tar.gz

# WORKDIR /roboliga_build/cmake-3.30.5
# RUN ./bootstrap
# RUN make
# RUN make install


# RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.11 0
RUN mv /home/robot/venv311 /home/robot/roboliga
RUN echo "home = /usr/local/bin\
include-system-site-packages = false\
version = 3.11.9\
executable = /usr/local/bin/python3.11\
command = /usr/local/bin/python3.11 -m venv /home/robot/roboliga\
" > /home/robot/roboliga/pyvenv.cfg
RUN echo "source /home/robot/roboliga/bin/activate" >> /home/robot/.bashrc

COPY ./requirements.txt /roboliga_build/requirements.txt

# USER robot
RUN source /home/robot/roboliga/bin/activate
RUN pip3.11 install -r /roboliga_build/requirements.txt

# Za ročne spremembe
# CMD ["sleep", "infinity"]